# congifuration for steps 

sudo: required # super user level permissions 
services:
  - docker

before_install:
  - docker build -t ks241/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ks241/docker-react npm run test -- --coverage